[env]
PATH = "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

[window]
decorations = "None" # This might be default, but explicitly setting for clarity
startup_mode = "Maximized"

[terminal]

[terminal.shell]
program = "tmux"
args = ["new-session", "-A", "-s", "main"]

[font]
size = 16.0
normal = { family = "Hack Nerd Font", style = "Regular" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold = { family = "Hack Nerd Font", style = "Bold" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }

# Colours (Monokai Charcoal)

# Default Colours
[colors.primary]
background = '#000000'
foreground = '#FFFFFF'

# Normal Colours
[colors.normal]
black   = '#1a1a1a'
red     = '#f4005f'
green   = '#98e024'
yellow  = '#fa8419'
blue    = '#9d65ff'
magenta = '#f4005f'
cyan    = '#58d1eb'
white   = '#c4c5b5'

# Bright Colours
[colors.bright]
black   = '#625e4c'
red     = '#f4005f'
green   = '#98e024'
yellow  = '#e0d561'
blue    = '#9d65ff'
magenta = '#f4005f'
cyan    = '#58d1eb'
white   = '#f6f6ef'
